# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Notebook

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

permissions:
    contents: read

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v3
            -   name: Set up Python 3.7
                uses: actions/setup-python@v3
                with:
                    python-version: "3.7"
            -   name: Install dependencies
                run: |
                    python -m pip install --upgrade pip
                    pip install torch numpy jupyter
            -   name: Convert notebook to python
                run: |
                    jupyter nbconvert gentle-introduction.ipynb --to python
            -   name: Run script
                run: |
                    ipython gentle-introduction.py
